In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import rebound
%matplotlib inline

In [28]:
path = '/mnt/ssd/workspace/stability/stabilitydataset/data/random/'
pathtofc = path+'final_conditions/runs/'
df = pd.read_csv(path+'random.csv', index_col=0)
df.tail()

         runstring
24995  0024995.bin
24996  0024996.bin
24997  0024997.bin
24998  0024998.bin
24999  0024999.bin

In [29]:
df['instability_time'] = -1
df['m1'] = -1
df['m2'] = -1
df['m3'] = -1
df['Stable'] = -1
df.head()

     runstring  instability_time  m1  m2  m3  Stable
0  0000000.bin                -1  -1  -1  -1      -1
1  0000001.bin                -1  -1  -1  -1      -1
2  0000002.bin                -1  -1  -1  -1      -1
3  0000003.bin                -1  -1  -1  -1      -1
4  0000004.bin                -1  -1  -1  -1      -1

In [30]:
def metadata(row):
    fc = rebound.Simulation.from_file(pathtofc+'fc'+row['runstring'])
    row['instability_time'] = fc.t
    row['m1'] = fc.particles[1].m
    row['m2'] = fc.particles[2].m
    row['m3'] = fc.particles[3].m
    row['Stable'] = fc.t > 9.99e8
    return row

In [31]:
df = df.apply(metadata, axis=1)

In [33]:
df.head()

,runstring,instability_time,m1,m2,m3,Stable
0,0000000.bin,1.235644e+07,3.414016e-05,1.878725e-05,1.826900e-06,False
1,0000001.bin,1.348749e+05,2.529838e-07,3.485790e-05,1.955797e-05,False
2,0000002.bin,1.276381e+04,7.380789e-05,6.974008e-05,1.477931e-07,False
3,0000003.bin,1.000000e+09,5.174804e-07,4.292276e-06,1.287851e-06,True
4,0000004.bin,8.791888e+01,5.106746e-07,2.039380e-07,1.542321e-06,False